name: Run Stock Analysis

on:
  workflow_dispatch:

jobs:
  analyze_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install baostock pandas numpy plotly openpyxl kaleido xlsxwriter
          
      - name: Download Release Asset for Manual Trigger
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          repo: 'cjbcmp/Stockdata'
          version: 'tags/latest-data'
          file: 'stock_kline_data.xlsx'
          target: 'stock_kline_data.xlsx'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run stock analysis script
        run: python Passive-Analysis.py

      - name: Upload generated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: |
            K_line_charts/
            low_volatility_stocks.xlsx
            low_volatility_stocks.jpg
          if-no-files-found: ignore
